twig:
    default_path: '%kernel.project_dir%/templates'

    globals :
        siteName : '%app.site_name%'
        trickImageUrl : '%trick_image_directory_url%'

when@test:
    twig:
        strict_variables: true
