parameters:
    app.site_name: 'Snowtricks'
    images_directory: '%kernel.project_dir%/public/uploads/images/'
    images_temporary: '%kernel.project_dir%/public/uploads/tmp/'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

