parameters:
    app.site_name: 'Snowtricks'
    upload_directory: '%kernel.project_dir%/public/uploads/'
    image_directory: '%upload_directory%images/tricks/'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
